### ISSUE TITLE
Detect whether users are administrators of the proposals repository and grant them moderator permissions on Metropolis

### ISSUE THREAD

**Issue by rjwebb** [canvasxyz/metropolis#10]
**Problem**:
We want to allow users who are administrators of the proposals repository (i.e. `filecoin-project/FIPs` ) permission to remove/modify proposals and moderate regular users of Metropolis. Currently every Metropolis user corresponds to a GitHub user, so we should be able to keep them in sync.

Administrators may be added and removed from the proposals repository, this change should then be reflected in Metropolis.

We may also need to update the GitHub App settings to grant permission to access the list of administrators for the repository.

**Possible solutions**:

- Perform a GitHub API request to check whether the user is an administrator every time they try to perform an action that requires admin access. This would be guaranteed to be up to date but would create a lot of API requests. However it would mean we would not need to store this information in the database.
- Create a webhook in the GitHub API that is called every time the repository configuration changes, this would then update a field in the database. This would also be guaranteed to be up to date but would require a bit more configuration in the GitHub app.
- Whenever GitHub sync is called or a user logs in (plus some other events?), sync our record of which users are administrators with the GitHub API.

**Additional context**:
Please add any other context or screenshots about the feature request here.

**Comment by raykyri** [comment]
I think the last one might actually be the most straightforward - fewer moving parts. The issue with the first option is that we would need to refetch permissions either on every view of the dashboard, or have some admin-specific page that users can navigate to, which bounces regular users when they try to access the page. But if we're going to do that, it's effectively the same as the last option

**Comment by rjwebb** [comment]
I think we can consider this one complete

**Comment by rjwebb** [comment]
Oh it was never merged... :|

**Comment by raykyri** [comment]
Implemented in #16 and https://github.com/canvasxyz/metropolis/commit/1acc536f50db8fd457b83675efcf3e0984c683b0.
