### ISSUE TITLE
Use GitHub user id for identifying users

### ISSUE THREAD

**Issue by rjwebb** [canvasxyz/metropolis#11]
We associate Metropolis users with GitHub users. Currently this is done using the GitHub username - this is not a good approach because a user could change their username, which could then be claimed by another person. We should instead use GitHub user ids.

**Proposed database change:**

Add a `github_user_id` column to the `users` table.

**Data migration:**

When we run github sync, iterate over all of the known users (i.e. the `users` table). If we know the Github username but not the GitHub user ID, then retrieve it from the GitHub API. We should use the user id to associate users with conversations in the GitHub sync code.

**Comment by raykyri** [comment]
This can be closed now?
