### ISSUE TITLE
Dashboard currently requests all fields of all conversations on load

### ISSUE THREAD

**Issue by rjwebb** [canvasxyz/metropolis#24]
Currently, the dashboard populates its list of conversations using the `GET /conversations` endpoint, which returns all of the conversations with (almost?) all of their fields, including the `description` field which is likely to be the largest one since it contains the proposal body text. This will lead to performance issues as the number of conversations increases (as a rough estimate, the total size of all of the FIPs on the filecoin-project repo is about 1.2MB).

A better solution would be to have the `GET /conversations` endpoint return a subset of the fields (title, submission date, submitter) and have the `GET /conversations?conversation_id=...` endpoint return the whole object.

**Comment by raykyri** [comment]
> i would just avoid changing GET /conversations  to return less data
> and instead have GET /conversationSummary that returns summarized data
> and GET /conversations?conversation_id=... return one conversation's full data

**Comment by raykyri** [comment]
Closed in #32.
