### ISSUE TITLE
Sidebar style

### ISSUE THREAD

**Issue by raykyri** [canvasxyz/metropolis#63]
Quick ticket:

* Limit number of items shown in the sidebar to five
* Underneath, add the "View all" button, and have it link to the FIPs tracker
* Add a "Sentiment Checks ▾" header but keep it as text, instead of a dropdown (I can do the final styling pass - I'll change the copy to something that makes more sense when I merge)

![image](https://github.com/user-attachments/assets/24f02bcc-86f8-4807-aefd-035ee1d85d0a)

**Comment by rjwebb** [comment]
Questions:
- In this new design, where will the "Create a poll" button go?
- The behaviour of the "View all" button could be confusing depending on whether we are viewing FIPs or Polls in the sidebar - I'd expect "View all" to go to the FIP Tracker if we have selected FIPs and go to the Sentiment Checks if we have selected Polls.
- What is the "Sentiment Checks ▾" dropdown going to be used for?

**Comment by raykyri** [comment]
* I would put the "Create a poll" button only on the Sentiment Checks page, in the top right *left* of the logged-in user display
* Let's have the View All button only show up when the sidebar is on FIPs or Polls - I'm looking into removing the All option (it could also just be hidden under All).
* Let's also change the copy from "Sentiment Checks ▾" to "Recently Active ▾"
