### ISSUE TITLE
Add "Only" selection buttons for "Status" and "Type" filters

### ISSUE THREAD

**Issue by raykyri** [canvasxyz/metropolis#66]

**Comment by rjwebb** [comment]
I think we should add "All" buttons as well for these filters.

**Comment by rjwebb** [comment]
Should we also add "All" buttons for these filters?

**Comment by rjwebb** [comment]
Going to add the "All" button question to a new issue https://github.com/canvasxyz/metropolis/issues/69

**Comment by rjwebb** [comment]
"Only" buttons implemented here https://github.com/canvasxyz/metropolis/pull/68
